# Default configuration for extension with alias: "rikudou_json_api"
rikudou_json_api:

    # The route prefix used with default routing file
    api_prefix:           /rest

    # Whether the bundle should hook into cache clearing process to clear the api cache
    clear_cache_hook:     true

    # Whether the bundle should look for all classes marked with ApiResource attribute and enable them automatically
    auto_discover_resources: true

    # The paths to scan for auto discovered endpoints
    auto_discover_paths:
        - '%kernel.project_dir%/src/Entity'

    # Disables automatic injection of resources that implement Rikudou\JsonApiBundle\Interfaces\ApiControllerInterface
    disable_autoconfiguration: false

    # A list of classes that will be imported. Useful in combination with disable_autoconfiguration
    enabled_resources:    []

    # The service that will be used to transform class names into resource names and property names into attribute names
    name_resolution_service: rikudou_api.name_resolution.camel_case

    # Set to true to enable pagination of resources
    pagination:           true

    # The limit of items per page used if no other limit was specified
    per_page_limit:       30

    # Set to true to automatically transfer DateTimeInterface objects to a string
    transform_datetime_objects: true

    # The date time format used if transform_datetime_objects is enabled
    datetime_format:      c

    # The cache adapter to use for caching properties etc.
    cache_adapter:        cache.app

    # Whether to allow overwriting of resources. This could happen if more than one controller for a resource with the same name exists.
    allow_resource_overwrite: false

